### PR TITLE
My recipe for Swedish pancakes

### PR DESCRIPTION
**Pull request by flooNetworker**

### CODE REVIEW

**Comment by marcnischan** [comment]
Hi TheMimi! 

Congrats on successfully submitting a pull request!! Before I merge this, I would like you to fix a couple of things. Somehow, your changes are spread across different sections of the cookbook. If you look under the "files changed" tab above, you will see your changes in green. 

If you could go back to your original document and putt them all together at the end then I can merge your recipe into the cookbook. Thanks!

**Comment by flooNetworker** [comment]
Now! It should be correct now. I put the recipe to the bottom of the README and pushed to the repo. Thank you for great lessons I learned a lot!

**Comment by marcnischan** [comment]
I love seeing all of the people from different parts of the world that take the class and add a recipe! Thanks for taking the class and be sure to post a screenshot in the class project section. If you are interested in coding websites with HTML & CSS I have two more classes on Skillshare. Good luck!

**Comment by flooNetworker** [comment]
Thank you, will do! Already started your next class!

**Pull request merged**
