### PR TITLE
Chonchon

### PR DESCRIPTION
**Pull request by chonchonj23**

### CODE REVIEW

**Comment by marcnischan** [comment]
Congrats on your pull request and thanks for taking the class!

**Comment by marcnischan** [comment]
I notice that you added "This is a student trial"... try removing this and adding a recipe and I will merge your pull request into the main repo. Thanks!

**Comment by chonchonj23** [comment]
Dear Marc,
Thank you very much for your email.
I was juggling several things in last few weeks, and finally managed to add "Oregano Breads" in the recipe README. Not sure if that pull request can reach you (just in case I did something silly).

Your Git & Github course is really helpful, and I now have a solid understanding of how Git & Github works.
Thank you again.

Best regards,Chon



    On Sunday, 16 February 2020, 09:50:13 GMT+8, Marc Nischan <notifications@github.com> wrote:  
 
 
I notice that you added "This is a student trial"... try removing this and adding a recipe and I will merge your pull request into the main repo. Thanks!

**Comment by marcnischan** [comment]
Hi Chon,

Thanks for submitting your pull request. There are no conflicts, but there is no recipe either. Essentially it’s blank. If you want to push something up there I’ll merge it. It can be as simple as a cup of tea or making toast :) Let me know if you’re stuck on anything, I want you to be able to add to the project!

Sincerely,
Marc

**Comment by marcnischan** [comment]
Closing this pull request due to inactivity.

**Pull request closed without merging**
