### PR TITLE
changed some text

### PR DESCRIPTION
**Pull request by Midnightknight**

### CODE REVIEW

**Comment by marcnischan** [comment]
Hi! Congratulations on submitting your pull request to the cookbook! Do you want to include any instructions with the ingredient list and re-submit before I merge this?

**Comment by Midnightknight** [comment]
Hey!
I think I’ll resubmit something else tomorrow.
Thank you, and I really enjoy your classes.
Best Regards,
Kenneth Lopez

**Comment by marcnischan** [comment]
Thanks! If you have any suggestions, I'm thinking of doin more. Thinking of doing a jQuery/JavaScript for visual learners, beginners, and everybody else. OK sounds good, I'll keep an eye on the inbox :)

**Comment by Midnightknight** [comment]
Awesome, thanks!

**Pull request merged**
